### ISSUE TITLE
S/D Zones

### ISSUE THREAD

**Issue by MarkkyL** [TradeArcher/TradeArcher#8]
Basically the zones should be created a candle after they are confirmed. There's 2 ways to for base rally and base drop.

So for example for a supply zone which is a sell zone, you want a basing candle then a drop, so the basing candle has to be a small green candle followed by a drop from a red candle and that candle size is about 200% bigger than the basing candle or bigger and it creates the zone on that closing candle and it stretches the zone out until price finally trades through it.

for demand zone, you want basing candle then rally up,  the basing candle has to be a small red candle then followed by a green candle that has the body size greater than 200% it creates the zone on the close of the candle and stretches it out until price trades through it.

For demand zone, it is drawn from the open of basing candle to the low of either the basing candle or rallying candle, which ever one has the lower price.

for supply zone, it is drawn from the open of basing candle to the high of either the base and the droping candle, which ever has the higher price.

![image](https://user-images.githubusercontent.com/75955093/102026596-b6f1e300-3d6c-11eb-87b7-6c7071ce1953.png)
First image of demand zone is from 2hr chart on the 3rd of this month.

![image](https://user-images.githubusercontent.com/75955093/102026694-3c759300-3d6d-11eb-8cf8-452e921c6a08.png)
Supply Zone is November 23rd on hourly chart. Something like this and it keeps drawing until price finally goes through it then it stops.

A feature that would help also not lag TOS if you can make it draw only a certain number of zones such as last 5 supply and last 5 demand zones

**Comment by TradeArcher2020** [comment]
The first version of this is completed in https://github.com/TradeArcher/TradeArcher/blob/master/ThinkScripts/ChartIndicators/SupplyAndDemandZones.txt

More enhancements to come, but this should suffice to close this issue.
